### ISSUE TITLE
Console message states that Our Groceries has been synced but no items are added

### ISSUE THREAD

**Issue by malbry** [jsetton/alexa-ourgroceries-sync#23]
Thanks for writing this skill and providing clear documentation on how to implement it. I have carefully followed the instructions and everything appears correctly implemented. I created the Security Profile along with the Allowed Return URL, all working as expected. The ask configure and ask deploy steps worked as expected. The account linking also worked as expected, including client ID, client secret in accountLinking.json and the ask smapi command including the skill ID.  In the Alexa app, I enabled the skill, linked my Amazon account and gave read and write list permissions. All exactly as described.

However the sync process is not working for me. Looking at the CloudWatch logs, the skill is correctly triggered when I add an item to the Alexa shopping list. I'm not seeing any error reported anywhere in the logs. However the added item doesn't hit my OurGroceries Shopping List. I have double-checked that my OurGroceries credentials are correctly shown in ask-resources.json and the OurGroceriesShoppingList is correctly shown as "Shopping List".

The only thing that looks unexpected to me in the logs is that the "OurGroceries shopping list has been synced" message is followed by {}, ie. JSON.stringify(attributes.syncedList) is returning nothing. This is from the index.js file. I'd be very grateful if you could suggest any further troubleshooting steps.

I previously had a hacky sync solution based on IFTTT, webhooks and some custom code running on a RaspPi. That no longer works since Amazon withdrew from IFTTT. So your skill, if I can get it working, will be a game-changer. Thanks!

**Comment by jsetton** [comment]
Are you sure that the added item was to the "Alexa shopping list"? From the message you provided, I would say the item wasn't added to your empty OurGroceries list at the time, because it wasn't from the expected Alexa list.

Keep in mind that if you aren't using the default Alexa shopping list, you need to configure the parameter `AlexaShoppingList` in `ask-resources.json`.

**Comment by malbry** [comment]
Thanks for the reply Jeremy. Yes, I am using the default Alexa shopping list. But to be sure, I have added "AlexaShoppingList": "Shopping" to the ask-resources.json file and run 'ask deploy' again to update the skill. But I'm still having the same problem as before: the skill triggers when I add an item to the Alexa shopping list but the item is not synced across to OurGroceries. 

The Cloudwatch log is showing a line "INFO Request received" with what looks to be a valid json including application ID, user ID, accessToken, consentToken, apiAccessToken and a request that looks like this:

"request": {
        "type": "AlexaHouseholdListEvent.ItemsCreated",
        "requestId": "19bed860-6148-4821-9c60-765e198e7ce2",
        "timestamp": "2023-11-03T08:23:58Z",
        "eventCreationTime": "2023-11-03T08:23:58Z",
        "eventPublishingTime": "2023-11-03T08:23:58Z",
        "body": {
            "listId": "YW16bjEuYWNjb3VudC5BRjZQUFRKTVhKQzI0V1c0M081WjRDVlBCN0ZRLVNIT1BQSU5HX0lURU0=",
            "listItemIds": [
                "4ed6014e-9c56-468f-af18-58d22fc3be63"
            ]
        }
    }

So that all looks OK to me. The only other thing to mention is that I'm in the UK and my endpoint is shown as "apiEndpoint": "https://api.eu.amazonalexa.com". Not sure that should make a difference though.

**Comment by malbry** [comment]
One more thing. I also get this warning during the ask deploy process.

[Warn]: {
  "message": "Skill api domain \"householdList\" cannot be enabled. Skipping the enable process.\n",
  "stack": "CliWarn: Skill api domain \"householdList\" cannot be enabled. Skipping the enable process.\n\n    at SkillMetadataController.validateDomain (C:\\Users\\Malcolm\\AppData\\Roaming\\npm\\node_modules\\ask-cli\\dist\\lib\\controllers\\skill-metadata-controller\\index.js:106:19)\n    at Object.enableSkill (C:\\Users\\Malcolm\\AppData\\Roaming\\npm\\node_modules\\ask-cli\\dist\\lib\\commands\\deploy\\helper.js:101:29)\n    at C:\\Users\\Malcolm\\AppData\\Roaming\\npm\\node_modules\\ask-cli\\dist\\lib\\commands\\deploy\\index.js:93:38\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "detail": {
    "name": "CliWarn"
  }
}

Up to now I've assumed that this is OK since the skill is still being triggered when a list event occurs. But maybe that's not a good assumption and I need to change something? As before, I'd be grateful for any suggestions. Thanks.

**Comment by jsetton** [comment]
> The only other thing to mention is that I'm in the UK and my endpoint is shown as "apiEndpoint": "https://api.eu.amazonalexa.com/"

Thanks that was the key information missing to understand your issue.

I just pushed a new release including support for regional api configuration. The important part is that since you are location in the UK, you should deploy your skill in `eu-west-1`. The deployment instructions have been updated. You should configure the parameter `awsRegion` in `ask-resources.json` accordingly, and make sure to remove the parameter `AlexaShoppingList` that you just added. The internal name for the Alexa shopping list is actually `Alexa shopping list` even though it displayed as `Shopping` in the Alexa App. So best to leave the skill use the default value.

I have also improved the error handling around the client synced list. An error should have been generated for your use case. Basically, when you enable the skill, it should initially sync your OurGroceries list to Alexa and store that list. On subsequent item events, the skill is expecting that list to be available. In your instance, the various Amazon-related API endpoints weren't pointing to the correct location. Most likely resulting in preventing the initial sync from completing.

As far as the `ask deploy` warning message you mentioned, this is expected and can be ignored.

**Comment by malbry** [comment]
Thank you for the quick response! I downloaded a new copy of the skill. I removed the AlexaShoppingList parameter from the ask-resources.json file and I changed the awsRegion to eu-west-1, leaving everything else unchanged (including the OurGroceries fields). I then used ask deploy to upload the updated version. As expected, this created a new skill with the same name in the developer console. I deleted the previous version. The updated skill now shows the language as 'English (IN) + 4'. So this all looks good. I then gave the 'ask smapi' command which completed successfully. In the Alexa app, I re-enabled the skill, went through the account linking process, and gave read & write permissions for lists.

The Cloudwatch logs now appear for region eu-west-1. Adding an item to the Alexa shopping list generates a log entry: "ERROR	Failed to handle household list items event: Not from our Alexa shopping list". I'm guessing that this is still some sort of region problem.

**Comment by jsetton** [comment]
Do you see an `AlexaSkillEvent.SkillPermissionAccepted` event in your logs when you enable the skill? If so, you should the synced list logged if successful.

**Comment by malbry** [comment]
I see the following as part of "INFO Request received":

"request": {
        "type": "AlexaSkillEvent.SkillPermissionAccepted",
        "requestId": "960a6832-a662-4ddc-8498-0749c01480ec",
        "timestamp": "2023-11-03T15:26:25Z",
        "eventCreationTime": "2023-11-03T15:26:25Z",
        "eventPublishingTime": "2023-11-03T15:28:17Z",
        "body": {
            "acceptedPermissions": [
                {
                    "scope": "alexa::household:lists:read"
                },
                {
                    "scope": "alexa::household:lists:write"
                }
            ]
        }
    }

I can't see a confirmation message in the logs saying that the request was successful.

**Comment by jsetton** [comment]
Are there log lines after that point indicating that "Alexa shopping list has been synced." followed by "User attributes have been saved." and "Event schedule has been created."?

**Comment by malbry** [comment]
I'm afraid not. Those log lines don't appear at all.

**Comment by jsetton** [comment]
Any error then? What's the subsequent log lines after the request was received?

**Comment by malbry** [comment]
2023-11-03T15:28:38.042Z b5f4e0b5-40af-4147-a95d-e3c213aa5e91 Task timed out after 20.14 seconds

END RequestId: b5f4e0b5-40af-4147-a95d-e3c213aa5e91

REPORT RequestId: b5f4e0b5-40af-4147-a95d-e3c213aa5e91	Duration: 20140.70 ms	Billed Duration: 20000 ms	Memory Size: 128 MB	Max Memory Used: 89 MB

**Comment by malbry** [comment]
Then a RequestId for items that I added to the shopping list, which generate the error I mentioned before.

**Comment by jsetton** [comment]
So the function is timing out waiting for the sync to happen. How big is your OurGroceries shopping list out of curiosity?

**Comment by malbry** [comment]
The current lists are quite small (<10 items) on both the Alexa and OurGroceries side. But there are a large number of 'completed' items on the Alexa list and 'Crossed off' items on the OurGroceries side. I had yesterday started to clean-up those entries, but it seemed to generate a very large number of consecutive skill events in the Cloudwatch logs (notwithstanding the sync didn't happen). So I decided to abandon that effort. By 'large number', I mean probably 100-200. Not talking thousands or anything like that. I would think that 20 seconds would be sufficient?

**Comment by jsetton** [comment]
> I had yesterday started to clean-up those entries, but it seemed to generate a very large number of consecutive skill events in the Cloudwatch logs (notwithstanding the sync didn't happen). So I decided to abandon that effort.

I would disable the skill and clean up your completed items on each side. The HouseholdList API doesn't seem to handle a large number of update at the same time. I actually increased the timeout from 5 to 20 in the latest release because I realized the scheduled OurGroceries sync was timing out on my end causing a tons of completed items to be stack on the Alexa side.

As a side note, I am concerned that the HouseholdList API may only be available in the US. The documentation only list the US [API endpoint](https://developer.amazon.com/en-US/docs/alexa/list-skills/list-management-api-reference.html#api-endpoint) and the Alexa SDK uses the api endpoint provided in the request to send HouseholdList API requests to.

**Comment by jsetton** [comment]
For the latter, [this Amazon Developer forum post](https://amazon.developer.forums.answerhub.com/questions/175837/get-status-code-403-in-python-when-trying-to-acces.html) seems to indicate it is supported although not documented.

So it could just be a matter of size as I mentioned in my previous message.

**Comment by malbry** [comment]
Well, you have my heartfelt thanks. Not only for writing the skill in the first place, but for your patience in helping me to get it working. I removed the completed/crossed off items as suggested, and items are now syncing from the Alexa list to OurGroceries. I haven't checked the other way, I will wait to see if that works but I'm confident that it will. 

Many thanks again for your help, you are a total star!

**Comment by jsetton** [comment]
> I haven't checked the other way, I will wait to see if that works but I'm confident that it will.

The initial sync is actually from OurGroceries list to Alexa. As long as the event schedule was created. That sync should occur every 30 minutes.
