### ISSUE TITLE
Sync to OurGroceries is broken

### ISSUE THREAD

**Issue by SeeThisIsMe** [jsetton/alexa-ourgroceries-sync#29]
From yesterday (July 1) the sync between Alexa and OurGroceries is broken. I Iooked into it a bit and think I have found the issue. In the developer console I saw this:

![image](https://github.com/jsetton/alexa-ourgroceries-sync/assets/53046241/437ce26f-e3c0-4984-81e3-cc344f08ca61)

And looking at the below link provided in the console

https://developer.amazon.com/en-US/docs/alexa/ask-overviews/deprecated-features.html#deprecated-business-skills

… I see this:

List Skills and Alexa Shopping and To-Do Lists
Starting July 1, 2024, you will no longer be able to use [List skills](https://developer.amazon.com/en-US/docs/alexa/list-skills/list-skills-overview.html) or the [List Management REST API](https://developer.amazon.com/en-US/docs/alexa/list-skills/list-management-api-reference.html) to access Alexa lists, i.e., the [Alexa Shopping and To-Do lists](https://developer.amazon.com/en-US/docs/alexa/custom-skills/access-the-alexa-shopping-and-to-do-lists.html), in your skills or apps. For other ways to build custom voice experiences, see [Steps to Build a Custom Skill](https://developer.amazon.com/en-US/docs/alexa/custom-skills/steps-to-build-a-custom-skill.html). Please [contact us](https://developer.amazon.com/en-US/docs/alexa/ask-overviews/contact-us.html) if you have any questions.

I assume everyone using this skill is probably affected. Any ideas on what needs to happen here?

Thanks!

**Comment by jsetton** [comment]
This is the end of this skill. You would have to go back and use the OurGroceries skill directly to add items to your list.
